domains                  = "tsanghan.dev.learnf5.cloud"
name                     = "tsanghan"
namespace                = "tsanghan"
origin_pool_service_name = "boutique-frontend.tsanghan"
origin_pool_virtual_site = "tsanghan-vsite"
